# Docker Compose file version

# Define all the services that make up our application
services:
  # The Backend Service
  backend:
    container_name: rh_backend_service
    build:
      context: ./rh-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}

  # The Frontend Service
  frontend:
    container_name: rh_frontend_service
    build:
      context: ./rh-frontend-updated
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      # Map port 8080 on your machine to port 80 in the container
      - "8080:80"